// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package jsonconfig

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComCryptoBundleBcWalletCommonLibConfigPkgJsonconfig(in *jlexer.Lexer, out *SimpleJSONCase) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "int_field_one":
			out.IntFieldOne = int(in.Int())
		case "int_field_tow":
			out.IntFieldTwo = int(in.Int())
		case "int_field_three":
			out.IntFieldThree = int(in.Int())
		case "string_field":
			out.StringField = string(in.String())
		case "float_field":
			out.FloatField = float32(in.Float32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComCryptoBundleBcWalletCommonLibConfigPkgJsonconfig(out *jwriter.Writer, in SimpleJSONCase) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"int_field_one\":"
		out.RawString(prefix[1:])
		out.Int(int(in.IntFieldOne))
	}
	{
		const prefix string = ",\"int_field_tow\":"
		out.RawString(prefix)
		out.Int(int(in.IntFieldTwo))
	}
	{
		const prefix string = ",\"int_field_three\":"
		out.RawString(prefix)
		out.Int(int(in.IntFieldThree))
	}
	{
		const prefix string = ",\"string_field\":"
		out.RawString(prefix)
		out.String(string(in.StringField))
	}
	{
		const prefix string = ",\"float_field\":"
		out.RawString(prefix)
		out.Float32(float32(in.FloatField))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SimpleJSONCase) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComCryptoBundleBcWalletCommonLibConfigPkgJsonconfig(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SimpleJSONCase) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComCryptoBundleBcWalletCommonLibConfigPkgJsonconfig(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SimpleJSONCase) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComCryptoBundleBcWalletCommonLibConfigPkgJsonconfig(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SimpleJSONCase) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComCryptoBundleBcWalletCommonLibConfigPkgJsonconfig(l, v)
}
